import os
import django
from datetime import datetime

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ceja_gestao.settings')
django.setup()

from professores.models import Professor, Disciplina, ConfiguracaoEscola, DisciplinaOfertada
from funcionarios.models import FuncionarioAdministrativo
from usuarios.models import Usuario

DADOS = [
    {
        "cpf": "01178363708",
        "nome": "Elazaro Moses Mokrabe",
        "id_vinculo": "32878745/2",
        "matricula": "9451022",
        "cargo": "PROF DOC I 18H NIVEL D REF 7",
        "disciplina_ingresso": "CIÊNCIAS FÍSICAS E BIOLÓGICAS",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2008-05-05",
        "data_nomeacao": "14/01/2009",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "8314270",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SEM MARCAÇÃO",
        "endereco": "RUA DOUTOR ODIM GÓIS",
        "numero": "250",
        "complemento": "RUA L CASA 6 B",
        "bairro": "TAQUARA",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "19/10/1972",
        "sexo": "M",
        "telefone": "",
        "celular": "(21) 96474-3734",
        "email_interno": "emokrabe@prof.educacao.rj.gov.br",
        "email_google": "elazaro.32878745@prof.educa.rj.gov.br",
        "email_alternativo": "mokrabe@hotmail.com"
    },
    {
        "cpf": "01329996763",
        "nome": "Sandra Helena Batista Da Silva",
        "id_vinculo": "39067432/1",
        "matricula": "8314544",
        "cargo": "PROF DOC I 30H NÍVEL D REF 9 - EX 18 HORAS",
        "disciplina_ingresso": "LÍNGUA PORTUGUESA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "1998-06-02",
        "data_nomeacao": "18/05/2026",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "RUA BELEM",
        "numero": "47",
        "complemento": "",
        "bairro": "CORÉIA",
        "municipio": "MESQUITA",
        "data_nascimento": "17/10/1967",
        "sexo": "F",
        "telefone": "(21)2697-0169",
        "celular": "(02)19859-0242",
        "email_interno": "sandrabatista@prof.educacao.rj.gov.br",
        "email_google": "sandra.39067432@prof.educa.rj.gov.br",
        "email_alternativo": "sandrabatista@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "01875683755",
        "nome": "Eliane Santos De Oliveira",
        "id_vinculo": "33230366/2",
        "matricula": "9363334",
        "cargo": "PROF DOC I 18H NIVEL D REF 7",
        "disciplina_ingresso": "EDUCAÇÃO FÍSICA",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2007-10-25",
        "data_nomeacao": "14/01/2009",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "33230366/1",
        "matricula_acumulacao": "50231752",
        "cargo_acumulacao": "PROF DOC I 40H NIVEL D REF 9",
        "disciplina_ingresso_acumulacao": "EDUCAÇÃO FÍSICA",
        "funcao_acumulacao": "REGENTE DOC I 40H",
        "ch_total_acumulacao": 40,
        "data_admissao_acumulacao": "1994-07-01",
        "situacao_matricula_2": "ativo",
        "acumulacao": "NÃO",
        "endereco": "RUA MENA BARRETO",
        "numero": "1109",
        "complemento": "",
        "bairro": "CENTRO",
        "municipio": "NILÓPOLIS",
        "data_nascimento": "29/10/1970",
        "sexo": "F",
        "telefone": "2127915430",
        "celular": "21983987242",
        "email_interno": "elianeoliveira@prof.educacao.rj.gov.br",
        "email_google": "eliane.33230366@prof.educa.rj.gov.br",
        "email_alternativo": "elianeoliveira@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "02582002780",
        "nome": "Arlindo De Mello Junior",
        "id_vinculo": "42809070/2",
        "matricula": "9447509",
        "cargo": "PROF DOC I 18H NIVEL C REF 6",
        "disciplina_ingresso": "MATEMÁTICA",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2008-04-11",
        "data_nomeacao": "28/01/2009",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "42809070/1",
        "matricula_acumulacao": "9300294",
        "cargo_acumulacao": "PROF DOC I 18H NIVEL C REF 6",
        "disciplina_ingresso_acumulacao": "MATEMÁTICA",
        "funcao_acumulacao": "REGENTE DOC I 18H",
        "ch_total_acumulacao": 18,
        "data_admissao_acumulacao": "2007-05-24",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SIM",
        "endereco": "RUA PROFESSOR SANTOS MOREIRA",
        "numero": "11",
        "complemento": "CASA 7",
        "bairro": "VARGEM PEQUENA",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "18/11/1975",
        "sexo": "M",
        "telefone": "(21) 3421-2662",
        "celular": "(21) 96432-5495",
        "email_interno": "ARLINDOJ@PROF.EDUCACAO.RJ.GOV.BR",
        "email_google": "arlindo.42809070@prof.educa.rj.gov.br",
        "email_alternativo": "ARLINDOJ@PROF.EDUCACAO.RJ.gov.br"
    },
    {
        "cpf": "03367411701",
        "nome": "Carlos Alberto Da Silva Laurindo",
        "id_vinculo": "20715870/2",
        "matricula": "9278862",
        "cargo": "PROF DOC I 18H NIVEL D REF 7",
        "disciplina_ingresso": "HISTÓRIA",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2006-02-06",
        "data_nomeacao": "16/01/2009",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "SEM MARCAÇÃO",
        "endereco": "Av Coelho da Rocha",
        "numero": "2095",
        "complemento": "casa 134",
        "bairro": "Rocha Sobrinho",
        "municipio": "MESQUITA",
        "data_nascimento": "10/08/1975",
        "sexo": "M",
        "telefone": "(21)3765-8043",
        "celular": "",
        "email_interno": "carloslaurindo@prof.educacao.rj.gov.br",
        "email_google": "carlos.20715870@prof.educa.rj.gov.br",
        "email_alternativo": "carloslaurindo@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "03828167730",
        "nome": "Elaine Ambrosio Souto Maior",
        "id_vinculo": "35002557/1",
        "matricula": "50159631",
        "cargo": "PROF DOC II40H NIVEL D REF 9",
        "disciplina_ingresso": "DOC II (ÁREA INTEGRADA)",
        "funcao": "PROFESSOR FACILITADOR DA METODOLOGIA EAD",
        "tipo_funcao": "EXTRACLASSE/CEJA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "1994-03-07",
        "data_nomeacao": "31/07/2024",
        "ch_planejamento": 0,
        "ch_regencia": 0,
        "ch_complementacao": 40,
        "ch_total": 40,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "RUA SAO MATEUS",
        "numero": "0",
        "complemento": "",
        "bairro": "NOVA CIDADE",
        "municipio": "NILÓPOLIS",
        "data_nascimento": "28/10/1974",
        "sexo": "F",
        "telefone": "",
        "celular": "",
        "email_interno": "elainemaior@prof.educacao.rj.gov.br",
        "email_google": "",
        "email_alternativo": "elainemaior@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "04280225702",
        "nome": "Viviane Souza De Freitas Da Silva",
        "id_vinculo": "42635217/1",
        "matricula": "9288572",
        "cargo": "PROF DOC I 30H NÍVEL C REF 6 - EX 18 HORAS",
        "disciplina_ingresso": "QUÍMICA",
        "funcao": "DIRETOR ADJUNTO",
        "tipo_funcao": "GRATIFICADA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2006-06-26",
        "data_nomeacao": "06/02/2025",
        "ch_planejamento": 0,
        "ch_regencia": 0,
        "ch_complementacao": 40,
        "ch_total": 40,
        "id_vinculo_acumulacao": "42635217/2",
        "matricula_acumulacao": "9416850",
        "cargo_acumulacao": "PROF DOC I 30H NÍVEL C REF 6 - EX 18 HORAS",
        "disciplina_ingresso_acumulacao": "QUÍMICA",
        "funcao_acumulacao": "REGENTE DOC I 30H",
        "ch_total_acumulacao": 30,
        "data_admissao_acumulacao": "2008-02-28",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SIM",
        "endereco": "RUA BARONESA",
        "numero": "162",
        "complemento": "APT 206 BLOCO 2",
        "bairro": "PRAÇA SECA",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "20/10/1975",
        "sexo": "F",
        "telefone": "(21)2501-1268",
        "celular": "(21)97565-1391",
        "email_interno": "vivianefreitas@prof.educacao.rj.gov.br",
        "email_google": "viviane.42635217@prof.educa.rj.gov.br",
        "email_alternativo": "vivifreitas36@gmail.com"
    },
    {
        "cpf": "05540420705",
        "nome": "Fabiana Rodrigues De Souza Pedro",
        "id_vinculo": "44161689/1",
        "matricula": "9721259",
        "cargo": "PROF DOC I 18H NIVEL D REF 6",
        "disciplina_ingresso": "LÍNGUA ESTRANGEIRA - ESPANHOL",
        "funcao": "DIRETOR ADJUNTO - ACUMULAÇÃO",
        "tipo_funcao": "ACUMULAÇÃO",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2011-08-01",
        "data_nomeacao": "06/04/2026",
        "ch_planejamento": 0,
        "ch_regencia": 0,
        "ch_complementacao": 18,
        "ch_total": 18,
        "id_vinculo_acumulacao": "44161689/3",
        "matricula_acumulacao": "31056526",
        "cargo_acumulacao": "PROF DOC I 30H NÍVEL D REF 5",
        "disciplina_ingresso_acumulacao": "LÍNGUA PORTUGUESA",
        "funcao_acumulacao": "DIRETOR ADJUNTO",
        "ch_total_acumulacao": 40,
        "data_admissao_acumulacao": "2018-02-08",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SIM",
        "endereco": "RUA AURELIA",
        "numero": "858",
        "complemento": "ANT.857",
        "bairro": "MESQUITA",
        "municipio": "MESQUITA",
        "data_nascimento": "16/03/1981",
        "sexo": "F",
        "telefone": "(21) 2796-4164",
        "celular": "",
        "email_interno": "fspedro@prof.educacao.rj.gov.br",
        "email_google": "fabiana.44161689@prof.educa.rj.gov.br",
        "email_alternativo": "secrosasoares@gmail.com"
    },
    {
        "cpf": "06991051705",
        "nome": "Izabel Cristina Da Cruz Pereira",
        "id_vinculo": "42108640/4",
        "matricula": "9703729",
        "cargo": "PROF DOC I 30H NÍVEL D REF 6 - EX 18 HORAS",
        "disciplina_ingresso": "LÍNGUA ESTRANGEIRA - INGLÊS",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2011-05-16",
        "data_nomeacao": "18/05/2026",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "9540881",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SIM",
        "endereco": "RUA MARCÍLIO DIAS",
        "numero": "11",
        "complemento": "",
        "bairro": "JARDIM MERITI",
        "municipio": "SÃO JOÃO DE MERITI",
        "data_nascimento": "15/03/1975",
        "sexo": "F",
        "telefone": "",
        "celular": "(21)99207-2086",
        "email_interno": "izabel.pereira@prof.educacao.rj.gov.br",
        "email_google": "izabel.42108640@prof.educa.rj.gov.br",
        "email_alternativo": "IZAPEREIRA@YAHOO.COM.BR"
    },
    {
        "cpf": "07117489774",
        "nome": "Luciana Da Silva Cavalcante",
        "id_vinculo": "42014310/1",
        "matricula": "9129990",
        "cargo": "PROF DOC I 18H NIVEL D REF 8",
        "disciplina_ingresso": "LÍNGUA ESTRANGEIRA - INGLÊS",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2005-02-01",
        "data_nomeacao": "17/02/2020",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "42014310/2",
        "matricula_acumulacao": "9330671",
        "cargo_acumulacao": "PROF DOC I 18H NIVEL D REF 7",
        "disciplina_ingresso_acumulacao": "LÍNGUA ESTRANGEIRA - INGLÊS",
        "funcao_acumulacao": "REGENTE DOC I 18H",
        "ch_total_acumulacao": 18,
        "data_admissao_acumulacao": "2007-05-24",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SIM",
        "endereco": "RUA OLIVA MAIA",
        "numero": "158",
        "complemento": "APT 201",
        "bairro": "MADUREIRA",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "16/05/1975",
        "sexo": "F",
        "telefone": "(21)3018-1545",
        "celular": "(02)18879-5289",
        "email_interno": "lucianacavalcante@prof.educacao.rj.gov.br",
        "email_google": "luciana.42014310@prof.educa.rj.gov.br",
        "email_alternativo": "lucianacavalcante@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "07152516782",
        "nome": "Alessandra Teixeira Batista Crespo",
        "id_vinculo": "41925912/5",
        "matricula": "9556275",
        "cargo": "PROF DOC I 30H NÍVEL D REF 7 - EX 18 HORAS",
        "disciplina_ingresso": "CIÊNCIAS FÍSICAS E BIOLÓGICAS",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2009-10-05",
        "data_nomeacao": "04/04/2025",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "9485939",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SEM MARCAÇÃO",
        "endereco": "RUA ROQUE BARRETO",
        "numero": "145",
        "complemento": "CASA FRENTE",
        "bairro": "PARQUE ANCHIETA",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "23/05/1976",
        "sexo": "F",
        "telefone": "(21)991271398",
        "celular": "(21)97537-9749",
        "email_interno": "alessandrat@prof.educacao.rj.gov.br",
        "email_google": "alessandra.41925912@prof.educa.rj.gov.br",
        "email_alternativo": "ALESSANDRATBC@HOTMAIL.COM"
    },
    {
        "cpf": "07353608714",
        "nome": "Thalles Yvson Alves De Souza",
        "id_vinculo": "43267211/1",
        "matricula": "9408238",
        "cargo": "PROF DOC I 18H NIVEL D REF 7",
        "disciplina_ingresso": "EDUCAÇÃO ARTÍSTICA",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2008-02-26",
        "data_nomeacao": "14/01/2009",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "RUA EX COMBATENTE",
        "numero": "355",
        "complemento": "",
        "bairro": "COELHO DA ROCHA",
        "municipio": "SÃO JOÃO DE MERITI",
        "data_nascimento": "11/04/1978",
        "sexo": "M",
        "telefone": "(21)8712-1839",
        "celular": "",
        "email_interno": "tyvson@prof.educacao.rj.gov.br",
        "email_google": "thalles.43267211@prof.educa.rj.gov.br",
        "email_alternativo": "tyvson@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "07612527707",
        "nome": "Fabiana De Paula Lessa Oliveira",
        "id_vinculo": "42611610/2",
        "matricula": "9336116",
        "cargo": "PROF DOC I 30H NÍVEL D REF 7 - EX 18 HORAS",
        "disciplina_ingresso": "LÍNGUA PORTUGUESA",
        "funcao": "COORDENADOR PEDAGÓGICO",
        "tipo_funcao": "GRATIFICADA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2007-05-28",
        "data_nomeacao": "22/05/2026",
        "ch_planejamento": 0,
        "ch_regencia": 0,
        "ch_complementacao": 40,
        "ch_total": 40,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "RUA DIVISA",
        "numero": "365",
        "complemento": "",
        "bairro": "SANTA EUGÊNIA",
        "municipio": "NOVA IGUAÇU",
        "data_nascimento": "01/06/1977",
        "sexo": "F",
        "telefone": "(21)2669-1737",
        "celular": "(21)971021636",
        "email_interno": "flessa@prof.educacao.rj.gov.br",
        "email_google": "fabiana.42611610@prof.educa.rj.gov.br",
        "email_alternativo": "FABIANAPL.OLIVEIRA@GMAIL.COM"
    },
    {
        "cpf": "07807234733",
        "nome": "Maxuell Rodrigues Xavier",
        "id_vinculo": "43870813/1",
        "matricula": "9644394",
        "cargo": "PROF DOC I 18H NIVEL C REF 6",
        "disciplina_ingresso": "MATEMÁTICA",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2010-06-22",
        "data_nomeacao": "17/06/2015",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "43870813/2",
        "matricula_acumulacao": "9721986",
        "cargo_acumulacao": "PROF DOC I 18H NIVEL C REF 5",
        "disciplina_ingresso_acumulacao": "MATEMÁTICA",
        "funcao_acumulacao": "REGENTE DOC I 18H",
        "ch_total_acumulacao": 18,
        "data_admissao_acumulacao": "2011-08-01",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SEM MARCAÇÃO",
        "endereco": "RUA BERNARDINO TILLIA",
        "numero": "531",
        "complemento": "",
        "bairro": "COELHO DA ROCHA",
        "municipio": "SÃO JOÃO DE MERITI",
        "data_nascimento": "04/05/1978",
        "sexo": "M",
        "telefone": "(21) 2751-1010",
        "celular": "(21) 97691-0056",
        "email_interno": "MAXUELL.XAVIER@PROF.EDUCACAO.RJ.GOV.BR",
        "email_google": "maxuell.43870813@prof.educa.rj.gov.br",
        "email_alternativo": "MAXUELL_MAT@YAHOO.COM.BR"
    },
    {
        "cpf": "08357310737",
        "nome": "Fernando Lima De Mesquita",
        "id_vinculo": "43268889/2",
        "matricula": "9626573",
        "cargo": "PROF DOC I 30H NÍVEL D REF 7 - EX 18 HORAS",
        "disciplina_ingresso": "FILOSOFIA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2010-06-07",
        "data_nomeacao": "08/11/2024",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "43268889/1",
        "matricula_acumulacao": "9415043",
        "cargo_acumulacao": "PROF DOC I 30H NÍVEL D REF 7 - EX 18 HORAS",
        "disciplina_ingresso_acumulacao": "FILOSOFIA",
        "funcao_acumulacao": "ORIENTADOR EDUCACIONAL",
        "ch_total_acumulacao": 40,
        "data_admissao_acumulacao": "2008-02-28",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SIM",
        "endereco": "RUA EGIDIO",
        "numero": "122",
        "complemento": "",
        "bairro": "CENTRO",
        "municipio": "MESQUITA",
        "data_nascimento": "05/03/1979",
        "sexo": "M",
        "telefone": "(21)2696-1056",
        "celular": "21981743115",
        "email_interno": "fmesquita@prof.educacao.rj.gov.br",
        "email_google": "fernando.43268889@prof.educa.rj.gov.br",
        "email_alternativo": "NANDOMESQUITA@YAHOO.COM.BR"
    },
    {
        "cpf": "08476030754",
        "nome": "Silvio Luiz Fernandes Freitas",
        "id_vinculo": "42032768/1",
        "matricula": "9171927",
        "cargo": "PROF DOC I 30H NÍVEL D REF 8 - EX 18 HORAS",
        "disciplina_ingresso": "MATEMÁTICA",
        "funcao": "DIRETOR ADJUNTO - ACUMULAÇÃO",
        "tipo_funcao": "ACUMULAÇÃO",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2005-02-01",
        "data_nomeacao": "25/06/2025",
        "ch_planejamento": 0,
        "ch_regencia": 0,
        "ch_complementacao": 30,
        "ch_total": 30,
        "id_vinculo_acumulacao": "42032768/2",
        "matricula_acumulacao": "30307292",
        "cargo_acumulacao": "PROF DOC I 30H NÍVEL D REF 6",
        "disciplina_ingresso_acumulacao": "MATEMÁTICA",
        "funcao_acumulacao": "DIRETOR ADJUNTO",
        "ch_total_acumulacao": 40,
        "data_admissao_acumulacao": "2012-06-18",
        "situacao_matricula_2": "ativo",
        "acumulacao": "NÃO",
        "endereco": "EST ELIZEU DE ALVARENGA",
        "numero": "1908",
        "complemento": "FDS -CASA2",
        "bairro": "CENTRO",
        "municipio": "NILÓPOLIS",
        "data_nascimento": "03/06/1981",
        "sexo": "M",
        "telefone": "(21)4137-1538",
        "celular": "(21)96445-4332",
        "email_interno": "SILVIOL@PROF.EDUCACAO.RJ.GOV.BR",
        "email_google": "silvio.42032768@prof.educa.rj.gov.br",
        "email_alternativo": "PROFESSORSILVIO@GMAIL.COM"
    },
    {
        "cpf": "08712473723",
        "nome": "Leandro De Oliveira Moreira",
        "id_vinculo": "41920678/2",
        "matricula": "9186669",
        "cargo": "PROF DOC I 30H NÍVEL D REF 8 - EX 18 HORAS",
        "disciplina_ingresso": "MATEMÁTICA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2005-02-01",
        "data_nomeacao": "02/12/2024",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "RUA CAIRUÇU",
        "numero": "259",
        "complemento": "APARTAMENTO 302",
        "bairro": "VILA VALQUEIRE",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "03/01/1975",
        "sexo": "M",
        "telefone": "(21)2768-2549",
        "celular": "(21)966021852",
        "email_interno": "leandroo@prof.educacao.rj.gov.br",
        "email_google": "leandro.41920678@prof.educa.rj.gov.br",
        "email_alternativo": "LEANDROMOREIRAS@YAHOO,COM.BR"
    },
    {
        "cpf": "08887099782",
        "nome": "Vitor Oliveira De Vasconcelos",
        "id_vinculo": "42097428/2",
        "matricula": "9443938",
        "cargo": "PROF DOC I 30H NÍVEL D REF 7 - EX 18 HORAS",
        "disciplina_ingresso": "GEOGRAFIA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2008-04-08",
        "data_nomeacao": "07/08/2024",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "SEM MARCAÇÃO",
        "endereco": "RUA COMENDADOR SOARES",
        "numero": "26",
        "complemento": "APTO 501B",
        "bairro": "CENTRO",
        "municipio": "NOVA IGUAÇU",
        "data_nascimento": "13/08/1981",
        "sexo": "M",
        "telefone": "21975584415",
        "celular": "(21)97558-4415",
        "email_interno": "VVASCONCELOS@PROF.EDUCACAO.RJ.GOV.BR",
        "email_google": "vitor.42097428@prof.educa.rj.gov.br",
        "email_alternativo": "ENGVITORVASCONCELOS@GMAIL.COM"
    },
    {
        "cpf": "09232801701",
        "nome": "Rafael De Amaral Maia",
        "id_vinculo": "43173896/1",
        "matricula": "9364506",
        "cargo": "PROF DOC I 30H NÍVEL D REF 7 - EX 18 HORAS",
        "disciplina_ingresso": "SOCIOLOGIA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2007-11-06",
        "data_nomeacao": "26/06/2025",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "30836761",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SIM",
        "endereco": "AV ALFREDO BALTAZAR DA SILVEIRA",
        "numero": "419",
        "complemento": "AP 408 BL 01",
        "bairro": "RECREIO DOS BANDEIRANTES",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "12/05/1982",
        "sexo": "M",
        "telefone": "(21)2005-9207",
        "celular": "(21)99888-3808",
        "email_interno": "RAFAELM@PROF.EDUCACAO.RJ.GOV.BR",
        "email_google": "rafael.43173896@prof.educa.rj.gov.br",
        "email_alternativo": "PROF.RAFAELMAIA@GMAIL.COM"
    },
    {
        "cpf": "09239576770",
        "nome": "Daniela Lima De Mesquita Matos",
        "id_vinculo": "42561086/1",
        "matricula": "9260407",
        "cargo": "PROF DOC I 30H NÍVEL D REF 7 - EX 18 HORAS",
        "disciplina_ingresso": "LÍNGUA PORTUGUESA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2006-02-06",
        "data_nomeacao": "18/05/2026",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "42561086/2",
        "matricula_acumulacao": "9505157",
        "cargo_acumulacao": "PROF DOC I 18H NIVEL D REF 7",
        "disciplina_ingresso_acumulacao": "LÍNGUA PORTUGUESA",
        "funcao_acumulacao": "REGENTE DOC I 18H",
        "ch_total_acumulacao": 18,
        "data_admissao_acumulacao": "2009-02-12",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SIM",
        "endereco": "RUA EGIDIO",
        "numero": "112",
        "complemento": "",
        "bairro": "CRUZEIRO DO SUL",
        "municipio": "MESQUITA",
        "data_nascimento": "21/03/1982",
        "sexo": "F",
        "telefone": "(21)2696-1056",
        "celular": "(21)98216-9702",
        "email_interno": "DMESQUITA@PROF.EDUCACAO.RJ.GOV.BR",
        "email_google": "daniela.42561086@prof.educa.rj.gov.br",
        "email_alternativo": "DLMESQUITA@YAHOO.COM.BR"
    },
    {
        "cpf": "09329367763",
        "nome": "Fabiane Silva Martins",
        "id_vinculo": "50098403/1",
        "matricula": "30347868",
        "cargo": "PROF DOC I 30H NÍVEL D REF 6 - EX 18 HORAS",
        "disciplina_ingresso": "HISTÓRIA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2012-12-05",
        "data_nomeacao": "07/08/2024",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "ETR DE CAMORIM",
        "numero": "1003",
        "complemento": "BL 03 - APT 108",
        "bairro": "JACAREPAGUÁ",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "28/04/1982",
        "sexo": "M",
        "telefone": "(21)2696-1056",
        "celular": "(21)99166-8179",
        "email_interno": "fabiane.50098403@prof.educacao.rj.gov.br",
        "email_google": "fabiane.50098403@prof.educa.rj.gov.br",
        "email_alternativo": "FABIANESILVAMARTINS@YAHOO.COM.BR"
    },
    {
        "cpf": "09330387713",
        "nome": "Marcela Costa Avila",
        "id_vinculo": "43323430/3",
        "matricula": "30337042",
        "cargo": "PROF DOC I 30H NÍVEL D REF 7",
        "disciplina_ingresso": "QUÍMICA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2012-11-01",
        "data_nomeacao": "04/12/2012",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "9446865",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SEM MARCAÇÃO",
        "endereco": "RUA SOUZA CALDAS",
        "numero": "154",
        "complemento": "CASA02",
        "bairro": "OSWALDO CRUZ",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "24/11/1982",
        "sexo": "F",
        "telefone": "(21)986833803",
        "celular": "(21)986833803",
        "email_interno": "marcelaa@prof.educacao.rj.gov.br",
        "email_google": "marcela.43323430@prof.educa.rj.gov.br",
        "email_alternativo": "MCOSTA.RJ@GMAIL.COM"
    },
    {
        "cpf": "09646240798",
        "nome": "Edilson Reis De Souza Junior",
        "id_vinculo": "43891489/2",
        "matricula": "9718420",
        "cargo": "PROF DOC I 30H NÍVEL D REF 6 - EX 18 HORAS",
        "disciplina_ingresso": "FÍSICA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2011-08-01",
        "data_nomeacao": "18/05/2026",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "9626649",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SIM",
        "endereco": "ETR DOUTOR MANUEL REIS",
        "numero": "110",
        "complemento": "BLOCO A AP 207",
        "bairro": "CENTRO",
        "municipio": "NILÓPOLIS",
        "data_nascimento": "25/07/1982",
        "sexo": "M",
        "telefone": "",
        "celular": "(21)96410-7663",
        "email_interno": "edilson.junior@prof.educacao.rj.gov.br",
        "email_google": "edilson.43891489@prof.educa.rj.gov.br",
        "email_alternativo": "EDILSON.JUNIOR@PROF.EDUCACAO.RJ.GOV.BR"
    },
    {
        "cpf": "10645794775",
        "nome": "Jordan De Aguiar Leal",
        "id_vinculo": "43877699/1",
        "matricula": "9617648",
        "cargo": "PROF DOC I 30H NÍVEL D REF 7 - EX 18 HORAS",
        "disciplina_ingresso": "MATEMÁTICA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2010-06-07",
        "data_nomeacao": "02/12/2024",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "SEM MARCAÇÃO",
        "endereco": "AVENIDA UNIÃO",
        "numero": "1333",
        "complemento": "FRENTE",
        "bairro": "CENTRO",
        "municipio": "MESQUITA",
        "data_nascimento": "25/05/1985",
        "sexo": "M",
        "telefone": "(21)2796-5900",
        "celular": "(21)97154-9958",
        "email_interno": "JORDAN.LEAL@PROF.EDUCACAO.RJ.GOV.BR",
        "email_google": "jordan.43877699@prof.educa.rj.gov.br",
        "email_alternativo": "AGUIARLEAL@YAHOO.COM.BR"
    },
    {
        "cpf": "11898131732",
        "nome": "Rafael Souza De Oliveira",
        "id_vinculo": "50264362/1",
        "matricula": "30589881",
        "cargo": "PROF DOC I 18H NIVEL D REF 6",
        "disciplina_ingresso": "LÍNGUA ESTRANGEIRA - ESPANHOL",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2014-03-13",
        "data_nomeacao": "17/03/2016",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "RUA PIO DUTRA",
        "numero": "211",
        "complemento": "CASA",
        "bairro": "FREGUESIA ILHA DO GOVERNADOR",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "10/01/1988",
        "sexo": "M",
        "telefone": "",
        "celular": "(21)98656-3380",
        "email_interno": "",
        "email_google": "rafael.50264362@prof.educa.rj.gov.br",
        "email_alternativo": "SOUZAUFRJ25@GMAIL.COM"
    },
    {
        "cpf": "11966771746",
        "nome": "Vitor Da Costa Souza",
        "id_vinculo": "50174789/1",
        "matricula": "30476170",
        "cargo": "PROF DOC I 30H NÍVEL D REF 6",
        "disciplina_ingresso": "MATEMÁTICA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2013-10-07",
        "data_nomeacao": "14/10/2021",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "RUA CACHOEIRA",
        "numero": "4",
        "complemento": "CASA 14",
        "bairro": "ROCHA SOBRINHO",
        "municipio": "MESQUITA",
        "data_nascimento": "24/03/1988",
        "sexo": "M",
        "telefone": "",
        "celular": "(21) 69403-1640",
        "email_interno": "vcostasouza@prof.educacao.rj.gov.br",
        "email_google": "vitor.50174789@prof.educa.rj.gov.br",
        "email_alternativo": "vitorsouza01@yahoo.com.br"
    },
    {
        "cpf": "12137462729",
        "nome": "Thamiris Dos Santos Couto",
        "id_vinculo": "43905129/1",
        "matricula": "9665225",
        "cargo": "PROF DOC I 30H NÍVEL D REF 6 - EX 18 HORAS",
        "disciplina_ingresso": "LÍNGUA PORTUGUESA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2010-08-11",
        "data_nomeacao": "28/07/2025",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "30538649",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SIM",
        "endereco": "Rua Arnaud Guedes de Amorim",
        "numero": "627",
        "complemento": "casa 1",
        "bairro": "Coelho da Rocha",
        "municipio": "SÃO JOÃO DE MERITI",
        "data_nascimento": "23/01/1988",
        "sexo": "F",
        "telefone": "(21) 7610-1066",
        "celular": "",
        "email_interno": "THAMIRIS.COUTO@PROF.EDUCACAO.RJ.GOV.BR",
        "email_google": "thamiris.43905129@prof.educa.rj.gov.br",
        "email_alternativo": "THAMIRIS.COUTO@PROF.EDUCACAO.RJ.gov.br"
    },
    {
        "cpf": "12419495730",
        "nome": "Leonardo Cesar De Oliveira Marques",
        "id_vinculo": "50347764/1",
        "matricula": "30713804",
        "cargo": "PROF DOC I 30H NÍVEL D REF 6",
        "disciplina_ingresso": "FÍSICA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2014-10-07",
        "data_nomeacao": "20/04/2026",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "30848071",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SEM MARCAÇÃO",
        "endereco": "AVENIDA MINISTRO LAFAYETE DE ANDRADE",
        "numero": "1683",
        "complemento": "BL.4 AP.602",
        "bairro": "MARCO II",
        "municipio": "NOVA IGUAÇU",
        "data_nascimento": "31/03/1989",
        "sexo": "M",
        "telefone": "",
        "celular": "(02) 16440-9111",
        "email_interno": "leonardomarques@prof.educacao.rj.gov.br",
        "email_google": "leonardo.50347764@prof.educa.rj.gov.br",
        "email_alternativo": ""
    },
    {
        "cpf": "37738631791",
        "nome": "Luis Carlos Henriques Monteiro",
        "id_vinculo": "40645924/2",
        "matricula": "2427227",
        "cargo": "PROF DOC I 30H NÍVEL D REF 9 - EX 18 HORAS",
        "disciplina_ingresso": "EDUCAÇÃO FÍSICA",
        "funcao": "DIRETOR DE ESCOLA",
        "tipo_funcao": "GRATIFICADA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "1985-05-20",
        "data_nomeacao": "04/04/2025",
        "ch_planejamento": 0,
        "ch_regencia": 0,
        "ch_complementacao": 40,
        "ch_total": 40,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "RUA ATLAS",
        "numero": "24",
        "complemento": "",
        "bairro": "CENTRO",
        "municipio": "NOVA IGUAÇU",
        "data_nascimento": "12/10/1955",
        "sexo": "M",
        "telefone": "(21)2667-5590",
        "celular": "(21)98658-5590",
        "email_interno": "lhenriques@prof.educacao.rj.gov.br",
        "email_google": "",
        "email_alternativo": "LHENRIQUES@PROF.EDUCACAO.RJ.GOV.BR"
    },
    {
        "cpf": "46044400778",
        "nome": "Gerson Do Nascimento",
        "id_vinculo": "39994856/2",
        "matricula": "2423853",
        "cargo": "PROF DOC I 18H NIVEL D REF 9",
        "disciplina_ingresso": "CIÊNCIAS FÍSICAS E BIOLÓGICAS",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "1985-05-20",
        "data_nomeacao": "15/01/2009",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "SIM",
        "endereco": "RUA JOAO FERREIRA GOULART",
        "numero": "40",
        "complemento": "",
        "bairro": "CENTRO",
        "municipio": "NOVA IGUAÇU",
        "data_nascimento": "05/06/1956",
        "sexo": "M",
        "telefone": "(21) 3103-2336",
        "celular": "(21) 99804-5879",
        "email_interno": "gersonn@prof.educacao.rj.gov.br",
        "email_google": "gerson.39994856@prof.educa.rj.gov.br",
        "email_alternativo": "gersonn@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "47770481791",
        "nome": "David Santos Da Cunha",
        "id_vinculo": "33289115/1",
        "matricula": "8396657",
        "cargo": "PROF DOC I 18H NIVEL D REF 9",
        "disciplina_ingresso": "GEOGRAFIA",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "1999-09-16",
        "data_nomeacao": "14/01/2009",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "rUA MAUA",
        "numero": "12",
        "complemento": "",
        "bairro": "SAO BERNARDO",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "26/03/1957",
        "sexo": "M",
        "telefone": "",
        "celular": "",
        "email_interno": "davidc@prof.educacao.rj.gov.br",
        "email_google": "david.33289115@prof.educa.rj.gov.br",
        "email_alternativo": "davidc@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "58694471515",
        "nome": "Delma Patricia Nunes Dos Santos",
        "id_vinculo": "42027756/1",
        "matricula": "9171968",
        "cargo": "PROF DOC I 30H NÍVEL D REF 8 - EX 18 HORAS",
        "disciplina_ingresso": "CIÊNCIAS FÍSICAS E BIOLÓGICAS",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2005-02-01",
        "data_nomeacao": "08/07/2026",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "COSMORAMA",
        "numero": "900",
        "complemento": "COND BEIJA FLOR 1 CASA 1",
        "bairro": "COSMORAMA",
        "municipio": "MESQUITA",
        "data_nascimento": "10/09/1969",
        "sexo": "F",
        "telefone": "(21)7318-5115",
        "celular": "(21)96952-1870",
        "email_interno": "DNUNES@PROF.EDUCACAO.RJ.GOV.BR",
        "email_google": "delma.42027756@prof.educa.rj.gov.br",
        "email_alternativo": "DPNSDELMA@GMAIL.COM"
    },
    {
        "cpf": "64423980720",
        "nome": "Jose Carlos Rodrigues De Carvalho",
        "id_vinculo": "34835075/1",
        "matricula": "50149939",
        "cargo": "PROF DOC I 40H NIVEL C REF 8",
        "disciplina_ingresso": "GEOGRAFIA",
        "funcao": "REGENTE DOC I 40H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "1994-03-07",
        "data_nomeacao": "01/01/2022",
        "ch_planejamento": 14,
        "ch_regencia": 26,
        "ch_complementacao": 0,
        "ch_total": 40,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "R MARIA EMILIA",
        "numero": "622",
        "complemento": "",
        "bairro": "CENTRO",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "27/09/1960",
        "sexo": "M",
        "telefone": "(21)2756-4088",
        "celular": "(02)18622-7610",
        "email_interno": "j.carvalho@prof.educacao.rj.gov.br",
        "email_google": "jose.34835075@prof.educa.rj.gov.br",
        "email_alternativo": "j.carvalho@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "70530890704",
        "nome": "Wanderley Farias De Souza",
        "id_vinculo": "42782490/1",
        "matricula": "9340043",
        "cargo": "PROF DOC I 18H NIVEL D REF 6",
        "disciplina_ingresso": "LÍNGUA ESTRANGEIRA - INGLÊS",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2007-06-11",
        "data_nomeacao": "14/01/2009",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "RUA TORQUATO TAPAJOS",
        "numero": "373",
        "complemento": "103",
        "bairro": "GUADALUPE",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "17/05/1961",
        "sexo": "M",
        "telefone": "",
        "celular": "(02)19414-6189",
        "email_interno": "wfarias@prof.educacao.rj.gov.br",
        "email_google": "wanderley.42782490@prof.educa.rj.gov.br",
        "email_alternativo": "wfarias@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "79888925768",
        "nome": "Mario Medeiros De Farias",
        "id_vinculo": "33421447/1",
        "matricula": "8255101",
        "cargo": "PROF DOC I 30H NÍVEL D REF 9 - EX 18 HORAS",
        "disciplina_ingresso": "HISTÓRIA",
        "funcao": "REGENTE DOC I 30H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "1998-02-09",
        "data_nomeacao": "18/05/2026",
        "ch_planejamento": 10,
        "ch_regencia": 20,
        "ch_complementacao": 0,
        "ch_total": 30,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "RUA JOSEFINA",
        "numero": "42",
        "complemento": "C",
        "bairro": "MIGUEL COUTO",
        "municipio": "NOVA IGUAÇU",
        "data_nascimento": "25/05/1965",
        "sexo": "M",
        "telefone": "(21)97933-6303",
        "celular": "(21)97933-6303",
        "email_interno": "MARIOMFARIAS@GMAIL.COM",
        "email_google": "mario.33421447@prof.educa.rj.gov.br",
        "email_alternativo": "MARIOMFARIAS@GMAIL.COM"
    },
    {
        "cpf": "81257805720",
        "nome": "Elinete Da Silva Aquino",
        "id_vinculo": "41875680/2",
        "matricula": "9193665",
        "cargo": "PROF DOC I 18H NIVEL C REF 7",
        "disciplina_ingresso": "SOCIOLOGIA",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2005-02-01",
        "data_nomeacao": "17/06/2015",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "30572200",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SIM",
        "endereco": "RUA VISCONDE DE ABAETÉ",
        "numero": "109",
        "complemento": "BL01 APTO 0501",
        "bairro": "VILA ISABEL",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "23/09/1962",
        "sexo": "F",
        "telefone": "(21)2577-9148",
        "celular": "(02)19674-9679",
        "email_interno": "elinetea@prof.educacao.rj.gov.br",
        "email_google": "elinete.41875680@prof.educa.rj.gov.br",
        "email_alternativo": "elinetea@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "84744898734",
        "nome": "Severino Batista De Oliveira",
        "id_vinculo": "33315892/1",
        "matricula": "50076496",
        "cargo": "ZELADOR VIGILANTE-CIEP",
        "disciplina_ingresso": "",
        "funcao": "ZELADOR",
        "tipo_funcao": "FUNCIONARIO",
        "regime_contratacao": "",
        "data_admissao": "2009-12-15",
        "data_nomeacao": "19/06/2023",
        "ch_planejamento": 40,
        "ch_regencia": 0,
        "ch_complementacao": 0,
        "ch_total": 40,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO É DOCENTE",
        "endereco": "AVENIDA BANDEIRANTE",
        "numero": "0",
        "complemento": "",
        "bairro": "BANDEIRANTE",
        "municipio": "NOVA IGUAÇU",
        "data_nascimento": "25/05/1963",
        "sexo": "M",
        "telefone": "",
        "celular": "",
        "email_interno": "",
        "email_google": "",
        "email_alternativo": ""
    },
    {
        "cpf": "87483246715",
        "nome": "Tania Maria S Ribeiro De Azevedo",
        "id_vinculo": "34259228/1",
        "matricula": "8405789",
        "cargo": "PROF DOCENTE II A REF 6",
        "disciplina_ingresso": "DOC II (EDUCAÇÃO ESPECIAL)",
        "funcao": "PROFESSOR FACILITADOR DA METODOLOGIA EAD",
        "tipo_funcao": "EXTRACLASSE/CEJA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2000-03-23",
        "data_nomeacao": "16/12/2019",
        "ch_planejamento": 0,
        "ch_regencia": 0,
        "ch_complementacao": 22,
        "ch_total": 22,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "RUA COSMORAMA",
        "numero": "700",
        "complemento": "COND. RUA TULIPAS CS 29",
        "bairro": "COSMORAMA",
        "municipio": "MESQUITA",
        "data_nascimento": "08/06/1962",
        "sexo": "F",
        "telefone": "(21)2792-4699",
        "celular": "",
        "email_interno": "taniaazevedo@prof.educacao.rj.gov.br",
        "email_google": "tania.34259228@prof.educa.rj.gov.br",
        "email_alternativo": "taniaazevedo@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "90591453720",
        "nome": "Iraci De Oliveira Costa Correia",
        "id_vinculo": "35021942/1",
        "matricula": "50206663",
        "cargo": "AGENTE ADM.BIBLIOTECA-CIEP",
        "disciplina_ingresso": "",
        "funcao": "AGENTE ADM",
        "tipo_funcao": "FUNCIONARIO",
        "regime_contratacao": "",
        "data_admissao": "1994-05-10",
        "data_nomeacao": "26/12/2017",
        "ch_planejamento": 40,
        "ch_regencia": 0,
        "ch_complementacao": 0,
        "ch_total": 40,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO É DOCENTE",
        "endereco": "RUA CIRIACO",
        "numero": "0",
        "complemento": "",
        "bairro": "MESQUITA",
        "municipio": "NOVA IGUAÇU",
        "data_nascimento": "25/02/1965",
        "sexo": "F",
        "telefone": "",
        "celular": "",
        "email_interno": "iracicorreia@educacao.rj.gov.br",
        "email_google": "",
        "email_alternativo": "iracicorreia@educacao.rj.gov.br"
    },
    {
        "cpf": "90854250778",
        "nome": "Noely Franca De Azevedo Monteiro",
        "id_vinculo": "35005874/1",
        "matricula": "50159730",
        "cargo": "PROF DOC II40H NIVEL D REF 9",
        "disciplina_ingresso": "DOC II (ÁREA INTEGRADA)",
        "funcao": "PROFESSOR FACILITADOR DA METODOLOGIA EAD",
        "tipo_funcao": "EXTRACLASSE/CEJA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "1994-03-07",
        "data_nomeacao": "20/07/2022",
        "ch_planejamento": 0,
        "ch_regencia": 0,
        "ch_complementacao": 40,
        "ch_total": 40,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "AVENIDA BRASIL",
        "numero": "1352",
        "complemento": "",
        "bairro": "COREIA",
        "municipio": "MESQUITA",
        "data_nascimento": "17/06/1964",
        "sexo": "F",
        "telefone": "(21)3765-9704",
        "celular": "(02)19981-5993",
        "email_interno": "noelim@prof.educacao.rj.gov.br",
        "email_google": "",
        "email_alternativo": "noelim@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "95708626704",
        "nome": "Luci Maria Da Silva Dornelles",
        "id_vinculo": "39538621/1",
        "matricula": "50206994",
        "cargo": "MERENDEIRA-CIEP",
        "disciplina_ingresso": "",
        "funcao": "SECRETÁRIO",
        "tipo_funcao": "GRATIFICADA",
        "regime_contratacao": "",
        "data_admissao": "1994-05-10",
        "data_nomeacao": "17/11/2020",
        "ch_planejamento": 40,
        "ch_regencia": 0,
        "ch_complementacao": 0,
        "ch_total": 40,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO É DOCENTE",
        "endereco": "RUA COSMORAMA",
        "numero": "197",
        "complemento": "BLOCO 13 AP 403",
        "bairro": "EDSON PASSOS",
        "municipio": "NOVA IGUAÇU",
        "data_nascimento": "01/05/1963",
        "sexo": "F",
        "telefone": "(21)2697-2379",
        "celular": "(21)99101-7519",
        "email_interno": "lucimariadasilvadornelles@educacao.rj.gov.br",
        "email_google": "",
        "email_alternativo": "lukdorneles@gmail.com"
    },
    {
        "cpf": "95831827704",
        "nome": "Rose Maria Da Fonseca Lima",
        "id_vinculo": "40124339/2",
        "matricula": "8388480",
        "cargo": "PROF DOC I 18H NIVEL D REF 9",
        "disciplina_ingresso": "EDUCAÇÃO FÍSICA",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "1999-07-12",
        "data_nomeacao": "20/02/2015",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO",
        "endereco": "RUA RAIMUNDO CORREA",
        "numero": "20",
        "complemento": "AP606",
        "bairro": "COPACABANA",
        "municipio": "RIO DE JANEIRO",
        "data_nascimento": "26/12/1967",
        "sexo": "F",
        "telefone": "(21)2596-6101",
        "celular": "(02)18270-3840",
        "email_interno": "rosel@prof.educacao.rj.gov.br",
        "email_google": "rose.40124339@prof.educa.rj.gov.br",
        "email_alternativo": "rosel@prof.educacao.rj.gov.br"
    },
    {
        "cpf": "97364029753",
        "nome": "Alexandre De Castro Nunes",
        "id_vinculo": "33289948/1",
        "matricula": "50087402",
        "cargo": "SERVENTE-CIEP",
        "disciplina_ingresso": "",
        "funcao": "SERVENTE",
        "tipo_funcao": "FUNCIONARIO",
        "regime_contratacao": "",
        "data_admissao": "1994-03-07",
        "data_nomeacao": "27/02/2015",
        "ch_planejamento": 40,
        "ch_regencia": 0,
        "ch_complementacao": 0,
        "ch_total": 40,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "n_a",
        "acumulacao": "NÃO É DOCENTE",
        "endereco": "RUA EDMUNDO BITTENCOURT",
        "numero": "153",
        "complemento": "",
        "bairro": "PONTO CHIQUE",
        "municipio": "NOVA IGUAÇU",
        "data_nascimento": "04/05/1968",
        "sexo": "M",
        "telefone": "",
        "celular": "(21)97182-6667",
        "email_interno": "",
        "email_google": "",
        "email_alternativo": "alexandrecastronunes59@gmail.com"
    },
    {
        "cpf": "99154625734",
        "nome": "Reinaldo Augusto Simoes",
        "id_vinculo": "5665809/5",
        "matricula": "9142126",
        "cargo": "PROF DOC I 18H NIVEL C REF 7",
        "disciplina_ingresso": "MATEMÁTICA",
        "funcao": "REGENTE DOC I 18H",
        "tipo_funcao": "REGÊNCIA",
        "regime_contratacao": "Concursado efetivo",
        "data_admissao": "2005-02-01",
        "data_nomeacao": "01/01/2016",
        "ch_planejamento": 6,
        "ch_regencia": 12,
        "ch_complementacao": 0,
        "ch_total": 18,
        "id_vinculo_acumulacao": "",
        "matricula_acumulacao": "9262841",
        "cargo_acumulacao": "",
        "disciplina_ingresso_acumulacao": "",
        "funcao_acumulacao": "",
        "ch_total_acumulacao": None,
        "data_admissao_acumulacao": "",
        "situacao_matricula_2": "ativo",
        "acumulacao": "SIM",
        "endereco": "RUA B",
        "numero": "110",
        "complemento": "AP 102",
        "bairro": "BARBOSA LAGE",
        "municipio": "JUIZ DE FORA",
        "data_nascimento": "15/04/1967",
        "sexo": "M",
        "telefone": "",
        "celular": "(21)98238-8397",
        "email_interno": "REINALDOS@PROF.EDUCACAO.RJ.GOV.BR",
        "email_google": "reinaldo.5665809@prof.educa.rj.gov.br",
        "email_alternativo": "REINALDOA13@YAHOO.COM"
    }
]

DISCIPLINAS_MATRIZ = [
    ("Língua Portuguesa", 6, 120),
    ("Matemática", 6, 120),
    ("História", 4, 80),
    ("Geografia", 4, 80),
    ("Biologia", 4, 80),
    ("Física", 4, 80),
    ("Química", 4, 80),
    ("Inglês", 2, 40),
    ("Espanhol", 2, 40),
    ("Sociologia", 2, 40),
    ("Filosofia", 2, 40),
    ("Artes", 2, 40),
    ("Educação Física", 2, 40),
    ("Ciências Físicas e Biológicas", 4, 80),
    ("Docência II (Área Integrada)", 4, 80),
]

def parse_d(val):
    if not val:
        return None
    val_str = str(val).strip()
    for fmt in ('%Y-%m-%d %H:%M:%S', '%Y-%m-%d', '%d/%m/%Y', '%Y/%m/%d'):
        try:
            return datetime.strptime(val_str, fmt).date()
        except ValueError:
            pass
    return None

def executar():
    print("Iniciando povoamento automatico com calculo automatico de C.H. por horas/aula...")
    
    config, _ = ConfiguracaoEscola.objects.get_or_create(
        ano_letivo=2026,
        defaults={
            'ativo': True, 'duracao_hora_aula': 50,
            'horario_abertura': '08:50', 'horario_fechamento': '20:30',
            'sex_abertura': '08:50', 'sex_fechamento': '17:00',
            'func_segunda': True, 'func_terca': True, 'func_quarta': True,
            'func_quinta': True, 'func_sexta': True, 'func_sabado': False, 'func_domingo': False
        }
    )

    # Criar Disciplinas e Ofertas padrao com CH calculada (horas_aula * 20 semanas)
    for d_nome, ha, ch_tot in DISCIPLINAS_MATRIZ:
        disc, _ = Disciplina.objects.get_or_create(nome=d_nome)
        DisciplinaOfertada.objects.update_or_create(
            configuracao=config,
            disciplina=disc,
            defaults={
                'horas_aula_semanais': ha,
                'carga_horaria_total': ch_tot,
                'ativo': True
            }
        )

    cpfs_reais = {r['cpf'] for r in DADOS}
    
    Professor.objects.all().delete()
    FuncionarioAdministrativo.objects.all().delete()
    
    usuarios_fakes = Usuario.objects.exclude(cpf='00000000000').exclude(cpf__in=cpfs_reais)
    usuarios_fakes.delete()

    adm_keywords = ['SERVENTE', 'AGENTE ADM', 'SECRETÁRIO', 'SECRETARIA', 'MERENDEIRA', 'ZELADOR', 'FACILITADOR', 'LEITURA']

    for r in DADOS:
        cpf_num = r['cpf']
        id_vinculo = r['id_vinculo']
        matricula = r['matricula']
        matricula_ac = r['matricula_acumulacao']
        nome = r['nome']
        cargo = r['cargo']
        disc_ing = r['disciplina_ingresso']
        funcao = r['funcao']
        tipo_funcao = r['tipo_funcao']
        regime = r['regime_contratacao']
        
        dt_adm = parse_d(r['data_admissao'])
        dt_nom = parse_d(r['data_nomeacao'])
        dt_nasc = parse_d(r['data_nascimento'])
        
        primary_email = r['email_google'] or r['email_interno'] or r['email_alternativo'] or (cpf_num + "@cejarosasoares.edu.br")

        is_adm = any(k in funcao.upper() for k in adm_keywords) or any(k in cargo.upper() for k in ['SERVENTE', 'MERENDEIRA', 'ZELADOR'])

        if is_adm:
            FuncionarioAdministrativo.objects.create(
                cpf=cpf_num, id_vinculo=id_vinculo, matricula=matricula,
                id_vinculo_acumulacao=r['id_vinculo_acumulacao'], matricula_acumulacao=matricula_ac,
                cargo_acumulacao=r['cargo_acumulacao'], disciplina_ingresso_acumulacao=r['disciplina_ingresso_acumulacao'],
                funcao_acumulacao=r['funcao_acumulacao'], ch_total_acumulacao=r['ch_total_acumulacao'],
                data_admissao_acumulacao=parse_d(r['data_admissao_acumulacao']),
                situacao_matricula_1='ativo', situacao_matricula_2=r.get('situacao_matricula_2', 'n_a'),
                nome_completo=nome, cargo=cargo, disciplina_ingresso=disc_ing, funcao_atual=funcao,
                funcao_ingresso=disc_ing, tipo_funcao=tipo_funcao, regime_contratacao=regime,
                data_admissao=dt_adm, data_nomeacao=dt_nom, data_ci_movimentacao=None, data_ingresso_unidade=None,
                ch_total=r['ch_total'], acumulacao=r['acumulacao'], data_nascimento=dt_nasc, sexo=r['sexo'],
                endereco=r['endereco'], numero=r['numero'], complemento=r['complemento'], bairro=r['bairro'],
                municipio=r['municipio'], email=r['email_interno'], email_google=r['email_google'],
                email_alternativo=r['email_alternativo'], telefone=r['telefone'], celular=r['celular'],
                classificacao=None, ativo=True
            )
            perfil_usuario = 'administrativo'
        else:
            prof = Professor.objects.create(
                cpf=cpf_num, id_vinculo=id_vinculo, matricula=matricula,
                id_vinculo_acumulacao=r['id_vinculo_acumulacao'], matricula_acumulacao=matricula_ac,
                cargo_acumulacao=r['cargo_acumulacao'], disciplina_ingresso_acumulacao=r['disciplina_ingresso_acumulacao'],
                funcao_acumulacao=r['funcao_acumulacao'], ch_total_acumulacao=r['ch_total_acumulacao'],
                data_admissao_acumulacao=parse_d(r['data_admissao_acumulacao']),
                situacao_matricula_1='ativo', situacao_matricula_2=r.get('situacao_matricula_2', 'n_a'),
                nome_completo=nome, cargo=cargo, disciplina_ingresso=disc_ing, funcao=funcao,
                tipo_funcao=tipo_funcao, regime_contratacao=regime, data_admissao=dt_adm, data_nomeacao=dt_nom,
                data_ci_movimentacao=None, data_ingresso_unidade=None, ch_planejamento=r['ch_planejamento'],
                ch_regencia=r['ch_regencia'], ch_complementacao=r['ch_complementacao'], ch_total=r['ch_total'],
                acumulacao=r['acumulacao'], data_nascimento=dt_nasc, sexo=r['sexo'], endereco=r['endereco'],
                numero=r['numero'], complemento=r['complemento'], bairro=r['bairro'], municipio=r['municipio'],
                email=r['email_interno'], email_google=r['email_google'], email_alternativo=r['email_alternativo'],
                telefone=r['telefone'], celular=r['celular'], classificacao=None, ativo=True
            )
            if disc_ing:
                d_found = Disciplina.objects.filter(nome__icontains=disc_ing.split(' ')[0]).first()
                if d_found:
                    prof.disciplinas_lecionadas.add(d_found)

            perfil_usuario = 'professor'

        if 'SILVIO LUIZ' in nome.upper():
            perfil_usuario = 'diretor'

        user = Usuario.objects.filter(cpf=cpf_num).first()
        if not user:
            if Usuario.objects.filter(email=primary_email).exists():
                primary_email = cpf_num + "@cejarosasoares.edu.br"
            Usuario.objects.create_user(
                cpf=cpf_num, nome_completo=nome, email=primary_email, perfil=perfil_usuario,
                password=cpf_num, id_vinculo=id_vinculo, matricula=matricula, telefone=r['celular'] or r['telefone']
            )
        else:
            user.nome_completo = nome
            user.id_vinculo = id_vinculo
            user.matricula = matricula
            if user.perfil != 'diretor':
                user.perfil = perfil_usuario
            user.save()

    print("Povoamento concluido com sucesso!")
    print(f"Disciplinas Ofertadas configuradas: {DisciplinaOfertada.objects.count()}")
    print(f"Professores: {Professor.objects.count()}")
    print(f"Administrativos: {FuncionarioAdministrativo.objects.count()}")
    print(f"Usuarios: {Usuario.objects.count()}")

if __name__ == '__main__':
    executar()
