# Generated by Django 6.0.6 on 2026-08-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('matricula_acumulacao', models.CharField(blank=True, max_length=20, verbose_name='Matrícula acumulação')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cargo', models.CharField(choices=[('ate', 'ATE — Agente de Trabalho em Educação'), ('assistente_secretaria', 'Assistente de Secretaria'), ('secretario', 'Secretário Escolar'), ('orientador', 'Orientador Educacional'), ('coordenador', 'Coordenador Pedagógico'), ('diretor_adjunto', 'Diretor Adjunto'), ('outro', 'Outro')], max_length=30, verbose_name='Cargo')),
                ('funcao_ingresso', models.CharField(help_text='Função original do concurso / admissão.', max_length=100, verbose_name='Função de ingresso')),
                ('data_ci_movimentacao', models.DateField(verbose_name='Data da CI de movimentação')),
                ('data_ingresso_unidade', models.DateField(verbose_name='Data de ingresso na unidade')),
                ('classificacao', models.PositiveIntegerField(blank=True, help_text='Ordem de chegada: 1 = funcionário com mais tempo na escola.', null=True, verbose_name='Classificação')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionarios/fotos/', verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo na escola')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de saída')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Funcionário Administrativo',
                'verbose_name_plural': 'Funcionários Administrativos',
                'ordering': ['classificacao', 'nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='FuncionarioTerceirizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('outro', 'Outro / Prefiro não informar')], max_length=10, verbose_name='Sexo')),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20, verbose_name='Estado civil')),
                ('naturalidade', models.CharField(blank=True, max_length=100, verbose_name='Naturalidade')),
                ('pis_pasep', models.CharField(blank=True, max_length=20, verbose_name='PIS/PASEP')),
                ('ctps_numero', models.CharField(blank=True, max_length=20, verbose_name='CTPS — Número')),
                ('ctps_serie', models.CharField(blank=True, max_length=10, verbose_name='CTPS — Série')),
                ('ctps_uf', models.CharField(blank=True, max_length=2, verbose_name='CTPS — UF')),
                ('empresa_contratante', models.CharField(max_length=200, verbose_name='Empresa contratante')),
                ('cargo_funcao', models.CharField(max_length=100, verbose_name='Cargo / Função')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário (R$)')),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de demissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, default='RJ', max_length=2, verbose_name='UF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('telefone_emergencia', models.CharField(blank=True, max_length=20, verbose_name='Telefone de emergência')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='terceirizados/fotos/', verbose_name='Foto')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Funcionário Terceirizado',
                'verbose_name_plural': 'Funcionários Terceirizados',
                'ordering': ['nome_completo'],
            },
        ),
    ]
