# Generated by Django 6.0.6 on 2026-08-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='disciplina_ingresso',
            field=models.CharField(blank=True, max_length=100, verbose_name='Disciplina de ingresso'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='funcao_atual',
            field=models.CharField(blank=True, max_length=100, verbose_name='Função Atual'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='id_vinculo',
            field=models.CharField(blank=True, help_text='Ex: 40260437/2', max_length=30, verbose_name='ID / Vínculo'),
        ),
        migrations.AlterField(
            model_name='funcionarioadministrativo',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionarioadministrativo',
            name='funcao_ingresso',
            field=models.CharField(blank=True, help_text='Função original do concurso / admissão.', max_length=100, verbose_name='Função de ingresso'),
        ),
    ]
