# Generated by Django 6.0.6 on 2026-08-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionarioadministrativo_disciplina_ingresso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='acumulacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Acumulação'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='celular',
            field=models.CharField(blank=True, max_length=50, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='ch_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CH Total'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='data_nomeacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nomeação'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='email_alternativo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail Alternativo'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='email_google',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail Google'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='endereco',
            field=models.CharField(blank=True, max_length=250, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='regime_contratacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Regime de Contratação'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='tipo_funcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Função'),
        ),
        migrations.AlterField(
            model_name='funcionarioadministrativo',
            name='cargo',
            field=models.CharField(max_length=150, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionarioadministrativo',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionarioadministrativo',
            name='data_ci_movimentacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da CI de movimentação'),
        ),
        migrations.AlterField(
            model_name='funcionarioadministrativo',
            name='data_ingresso_unidade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de ingresso na unidade'),
        ),
        migrations.AlterField(
            model_name='funcionarioadministrativo',
            name='disciplina_ingresso',
            field=models.CharField(blank=True, max_length=150, verbose_name='Disciplina de ingresso'),
        ),
        migrations.AlterField(
            model_name='funcionarioadministrativo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail Interno'),
        ),
        migrations.AlterField(
            model_name='funcionarioadministrativo',
            name='funcao_atual',
            field=models.CharField(blank=True, max_length=150, verbose_name='Função Atual'),
        ),
        migrations.AlterField(
            model_name='funcionarioadministrativo',
            name='funcao_ingresso',
            field=models.CharField(blank=True, help_text='Função original do concurso / admissão.', max_length=150, verbose_name='Função de ingresso'),
        ),
        migrations.AlterField(
            model_name='funcionarioadministrativo',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefone'),
        ),
    ]
