# Generated by Django 6.0.6 on 2026-08-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionarioadministrativo_acumulacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='cargo_acumulacao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cargo (2ª Matrícula)'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='ch_total_acumulacao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CH Total (2ª Matrícula)'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='data_admissao_acumulacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Admissão (2ª Matrícula)'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='disciplina_ingresso_acumulacao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Disciplina de Ingresso (2ª Matrícula)'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='funcao_acumulacao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Função (2ª Matrícula)'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='id_vinculo_acumulacao',
            field=models.CharField(blank=True, max_length=30, verbose_name='ID / Vínculo (2ª Matrícula)'),
        ),
        migrations.AlterField(
            model_name='funcionarioadministrativo',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
