# Generated by Django 6.0.6 on 2026-08-27 17:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_funcionarioadministrativo_situacao_matricula_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarioterceirizado',
            name='senha_ponto',
            field=models.CharField(blank=True, help_text='PIN ou Senha individual para bater o ponto', max_length=128, verbose_name='Senha do Ponto'),
        ),
        migrations.CreateModel(
            name='RegistroPontoTerceirizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Chegando à escola)'), ('ALMOCO_SAIDA', 'Saída para Almoço'), ('ALMOCO_RETORNO', 'Retorno do Almoço'), ('SAIDA', 'Saída para Casa (Fim de expediente)')], max_length=20, verbose_name='Tipo de Registro')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora da Batida')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='terceirizados/ponto/', verbose_name='Foto da Batida')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação / Justificativa')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Confirmação por E-mail Enviada')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='funcionarios.funcionarioterceirizado', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Registro de Ponto (Terceirizado)',
                'verbose_name_plural': 'Registros de Ponto (Terceirizados)',
                'ordering': ['-data_hora'],
            },
        ),
    ]
