# Generated by Django 6.0.6 on 2026-08-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_funcionarioterceirizado_senha_ponto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarioterceirizado',
            name='centro_custo',
            field=models.CharField(blank=True, default='CEJA-MESQUITA - PROF ROSA SOARES', max_length=150, verbose_name='Centro de Custo (C. Custo)'),
        ),
        migrations.AddField(
            model_name='funcionarioterceirizado',
            name='codigo_terceirizado',
            field=models.CharField(blank=True, help_text='Ex: 176, 26', max_length=20, verbose_name='Código / Matrícula na Empresa'),
        ),
        migrations.AddField(
            model_name='funcionarioterceirizado',
            name='departamento',
            field=models.CharField(blank=True, default='CECIERJ', max_length=100, verbose_name='Departamento (DPTO)'),
        ),
        migrations.AddField(
            model_name='funcionarioterceirizado',
            name='empresa_bairro',
            field=models.CharField(blank=True, default='JARDIM GUANABARA', max_length=100, verbose_name='Bairro da Empresa'),
        ),
        migrations.AddField(
            model_name='funcionarioterceirizado',
            name='empresa_cep',
            field=models.CharField(blank=True, default='21931-383', max_length=10, verbose_name='CEP da Empresa'),
        ),
        migrations.AddField(
            model_name='funcionarioterceirizado',
            name='empresa_cidade',
            field=models.CharField(blank=True, default='RIO DE JANEIRO', max_length=100, verbose_name='Cidade da Empresa'),
        ),
        migrations.AddField(
            model_name='funcionarioterceirizado',
            name='empresa_cnpj',
            field=models.CharField(blank=True, default='33.780.199/0001-77', max_length=20, verbose_name='CNPJ da Empresa'),
        ),
        migrations.AddField(
            model_name='funcionarioterceirizado',
            name='empresa_endereco',
            field=models.CharField(blank=True, default='ESTRADA DO GALEAO, 1285', max_length=250, verbose_name='Endereço da Empresa'),
        ),
        migrations.AddField(
            model_name='funcionarioterceirizado',
            name='empresa_uf',
            field=models.CharField(blank=True, default='RJ', max_length=2, verbose_name='UF da Empresa'),
        ),
        migrations.AddField(
            model_name='funcionarioterceirizado',
            name='horario_trabalho',
            field=models.CharField(blank=True, default='07:00 X 16:48', help_text='Ex: 07:00 X 16:48', max_length=50, verbose_name='Horário de Trabalho'),
        ),
        migrations.AlterField(
            model_name='funcionarioterceirizado',
            name='empresa_contratante',
            field=models.CharField(default='KRATUS TECNOLOGIA COMERCIO E SERVICOS LT', max_length=200, verbose_name='Empresa Contratante'),
        ),
    ]
