# Generated by Django 6.0.6 on 2026-09-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_funcionarioterceirizado_centro_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='data_ci_movimentacao_acumulacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da CI de Movimentação (2ª Matrícula)'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='data_ingresso_unidade_acumulacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Chegada na Escola / Ingresso (2ª Matrícula)'),
        ),
        migrations.AlterField(
            model_name='funcionarioadministrativo',
            name='data_admissao_acumulacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Admissão no Estado (2ª Matrícula)'),
        ),
    ]
