# Generated by Django 6.0.6 on 2026-08-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_funcionario', models.CharField(choices=[('professor', 'Professor'), ('administrativo', 'Funcionário Administrativo'), ('terceirizado', 'Funcionário Terceirizado')], max_length=20, verbose_name='Tipo de funcionário')),
                ('professor_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Professor (ID)')),
                ('administrativo_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Funcionário Administrativo (ID)')),
                ('terceirizado_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Funcionário Terceirizado (ID)')),
                ('nome_funcionario', models.CharField(help_text='Preenchido automaticamente.', max_length=200, verbose_name='Nome do funcionário')),
                ('data', models.DateField(verbose_name='Data da ocorrência')),
                ('tipo', models.CharField(choices=[('falta', 'Falta'), ('ausencia', 'Ausência justificada'), ('atraso', 'Atraso'), ('saida_antecipada', 'Saída antecipada')], max_length=20, verbose_name='Tipo')),
                ('hora_chegada', models.TimeField(blank=True, help_text='Preencha apenas para atrasos.', null=True, verbose_name='Hora de chegada')),
                ('hora_saida', models.TimeField(blank=True, help_text='Preencha apenas para saídas antecipadas.', null=True, verbose_name='Hora de saída')),
                ('justificado', models.BooleanField(default=False, verbose_name='Justificado')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Presença',
                'verbose_name_plural': 'Registros de Presença',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ReservaAuditorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do evento')),
                ('tipo', models.CharField(choices=[('oficina', 'Oficina'), ('aula', 'Aula'), ('evento', 'Evento / Palestra'), ('reuniao', 'Reunião'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Detalhes')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Horário de início')),
                ('hora_fim', models.TimeField(verbose_name='Horário de término')),
                ('responsavel', models.CharField(help_text='Nome do professor ou organizador.', max_length=200, verbose_name='Responsável pelo evento')),
                ('turma_publico', models.CharField(blank=True, max_length=200, verbose_name='Turma / Público alvo')),
                ('capacidade_prevista', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade prevista (nº de pessoas)')),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('pendente', 'Pendente'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], default='confirmada', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reserva do Auditório',
                'verbose_name_plural': 'Reservas do Auditório',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
    ]
