# Generated by Django 6.0.6 on 2026-09-14 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
        ('professores', '0015_professor_abrangencia_desvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropresenca',
            name='dias_banco_horas',
            field=models.DecimalField(decimal_places=1, default=0.5, help_text='Ex: 0.5 dia, 1.0 dia', max_digits=4, verbose_name='Equivalente em Dias no Banco'),
        ),
        migrations.AddField(
            model_name='registropresenca',
            name='lancar_banco_horas',
            field=models.BooleanField(default=True, verbose_name='Lançar no Banco de Horas / Folgas'),
        ),
        migrations.AddField(
            model_name='registropresenca',
            name='ocorrencia_folga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_presenca', to='professores.ocorrenciafolgaservidor', verbose_name='Lançamento no Banco de Horas'),
        ),
        migrations.AlterField(
            model_name='registropresenca',
            name='tipo',
            field=models.CharField(choices=[('falta', 'Falta'), ('ausencia', 'Ausência justificada'), ('atraso', 'Atraso'), ('saida_antecipada', 'Saída antecipada'), ('compensacao', 'Compensação de horas (Crédito)')], max_length=20, verbose_name='Tipo'),
        ),
    ]
