# Generated by Django 6.0.6 on 2026-10-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_registropresenca_dias_banco_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropresenca',
            name='minutos_total',
            field=models.IntegerField(default=50, verbose_name='Total de Minutos Computados'),
        ),
        migrations.AddField(
            model_name='registropresenca',
            name='quantidade_tempo',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5, verbose_name='Quantidade de Tempo Informada'),
        ),
        migrations.AddField(
            model_name='registropresenca',
            name='unidade_tempo',
            field=models.CharField(choices=[('tempos', 'Tempos de Aula (50 min cada)'), ('minutos', 'Minutos Exatos'), ('horas', 'Horas Cheias'), ('dias', 'Dia(s) Inteiro(s)')], default='tempos', max_length=20, verbose_name='Unidade de Lançamento'),
        ),
    ]
