# Generated by Django 6.0.6 on 2026-09-21 20:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoSEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sei', models.CharField(help_text='Ex: SEI-030029/000123/2026', max_length=80, unique=True, verbose_name='Número do Processo SEI')),
                ('titulo', models.CharField(help_text='Identificação rápida do assunto principal', max_length=255, verbose_name='Assunto / Resumo do Processo')),
                ('palavras_chave', models.CharField(blank=True, help_text='Termos de busca rápida (ex: Reforma, Lotação, Prestação de Contas, GLPI, Merenda)', max_length=255, verbose_name='Palavras-chave')),
                ('descricao', models.TextField(blank=True, help_text='Explicação clara do processo para leitura e compreensão imediata', verbose_name='Descrição / Observações')),
                ('interessado', models.CharField(blank=True, help_text='Nome do servidor, setor ou requerente', max_length=200, verbose_name='Interessado / Requerente')),
                ('setor_atual', models.CharField(blank=True, help_text='Onde o processo está tramitando (ex: SEEDUC/DGE, DIESP, Regional Metropolitana I, etc.)', max_length=150, verbose_name='Setor / Unidade Atual')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('aguardando_resposta', 'Aguardando Resposta / Parecer'), ('sob_analise', 'Sob Análise'), ('concluido', 'Concluído / Deferido'), ('arquivado', 'Arquivado'), ('indeferido', 'Indeferido')], default='em_andamento', max_length=30, verbose_name='Status / Situação')),
                ('prioridade', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridade')),
                ('data_abertura', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Abertura / Registro')),
                ('link_sei', models.URLField(blank=True, help_text='Link opcional para abrir diretamente o processo no sistema SEI', verbose_name='Link de Acesso Direto no SEI')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro no Sistema')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Processo SEI',
                'verbose_name_plural': 'Processos SEI',
                'ordering': ['-data_abertura', '-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='AndamentoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Andamento')),
                ('descricao', models.TextField(verbose_name='Despacho / Anotação de Acompanhamento')),
                ('setor', models.CharField(blank=True, max_length=150, verbose_name='Setor / Local Envolvido')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='processos.processosei', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Andamento do Processo',
                'verbose_name_plural': 'Andamentos do Processo',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
