# Generated by Django 6.0.6 on 2026-09-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processosei',
            name='tipo',
            field=models.CharField(choices=[('pessoal_rh', 'Pessoal & RH (Lotação, Licenças, GLPI, Aposentadoria)'), ('infraestrutura', 'Infraestrutura & Obras (Reforma, Reparos, Manutenção)'), ('pedagogico', 'Pedagógico & Alunos (Censo, Certificação, Projetos)'), ('financeiro_compras', 'Financeiro & Compras (PDDE, Prestação de Contas, Verbas)'), ('merenda_alimentacao', 'Alimentação & Merenda Escolar'), ('tecnologia_ti', 'Tecnologia & Informática (Computadores, Redes, TI)'), ('administrativo_geral', 'Administrativo Geral & Expediente'), ('outros', 'Outros')], default='administrativo_geral', help_text='Área de classificação para organização e filtros rápidos', max_length=40, verbose_name='Tipo / Categoria do Processo'),
        ),
    ]
