# Generated by Django 6.0.6 on 2026-09-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0008_funcionarioadministrativo_data_ci_movimentacao_acumulacao_and_more'),
        ('processos', '0002_processosei_tipo'),
        ('professores', '0016_professor_data_ci_movimentacao_acumulacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processosei',
            name='administrativos_relacionados',
            field=models.ManyToManyField(blank=True, help_text='Servidores administrativos atrelados a este processo SEI', related_name='processos_sei', to='funcionarios.funcionarioadministrativo', verbose_name='Funcionários Administrativos Relacionados'),
        ),
        migrations.AddField(
            model_name='processosei',
            name='professores_relacionados',
            field=models.ManyToManyField(blank=True, help_text='Docentes atrelados a este processo SEI', related_name='processos_sei', to='professores.professor', verbose_name='Professores Relacionados'),
        ),
    ]
