# Generated by Django 6.0.6 on 2026-08-21 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cpf', models.CharField(help_text='Somente números, 11 dígitos.', max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('perfil', models.CharField(choices=[('diretor', 'Diretor'), ('professor', 'Professor'), ('administrativo', 'Funcionário Administrativo'), ('terceirizado', 'Funcionário Terceirizado')], max_length=20, verbose_name='Perfil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso ao Admin')),
                ('primeiro_acesso', models.BooleanField(default=True, help_text='Se verdadeiro, o usuário será obrigado a trocar a senha.', verbose_name='Primeiro acesso')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de cadastro')),
                ('ultimo_login_sistema', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
                ('token_recuperacao', models.CharField(blank=True, max_length=100, verbose_name='Token de recuperação')),
                ('token_expiracao', models.DateTimeField(blank=True, null=True, verbose_name='Expiração do token')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome_completo'],
            },
        ),
    ]
