# Generated by Django 6.0.6 on 2026-08-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_vinculo',
            field=models.CharField(blank=True, help_text='Ex: 40645924/2', max_length=30, verbose_name='ID / Vínculo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, help_text='Ex: 2427227', max_length=30, verbose_name='Matrícula'),
        ),
    ]
