# Generated by Django 6.0.6 on 2026-09-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_id_vinculo_usuario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('diretor', 'Diretor'), ('coordenador_pedagogico', 'Coordenador Pedagógico'), ('orientador_educacional', 'Orientador Educacional'), ('professor', 'Professor'), ('administrativo', 'Funcionário Administrativo'), ('terceirizado', 'Funcionário Terceirizado')], max_length=30, verbose_name='Perfil'),
        ),
    ]
