# Generated by Django 6.0.6 on 2026-08-21 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Disciplina')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Área do conhecimento')),
                ('cor', models.CharField(default='#1565C0', max_length=7, verbose_name='Cor (hex)')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='Somente números.', max_length=11, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('matricula_acumulacao', models.CharField(blank=True, help_text='Preencha apenas se o professor acumula cargo.', max_length=20, verbose_name='Matrícula acumulação')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cargo', models.CharField(choices=[('professor_i', 'Professor I'), ('professor_ii', 'Professor II'), ('professor_adjunto_i', 'Professor Adjunto I'), ('professor_adjunto_ii', 'Professor Adjunto II'), ('outro', 'Outro')], max_length=30, verbose_name='Cargo')),
                ('disciplina_ingresso', models.CharField(choices=[('portugues', 'Língua Portuguesa'), ('ingles', 'Língua Inglesa'), ('espanhol', 'Língua Espanhola'), ('artes', 'Artes / Educação Artística'), ('educacao_fisica', 'Educação Física'), ('biologia', 'Ciências / Biologia'), ('quimica', 'Química'), ('fisica', 'Física'), ('historia', 'História'), ('geografia', 'Geografia'), ('filosofia', 'Filosofia'), ('sociologia', 'Sociologia'), ('matematica', 'Matemática'), ('outro', 'Outro')], help_text='Disciplina do concurso público / admissão.', max_length=30, verbose_name='Disciplina de ingresso')),
                ('data_ci_movimentacao', models.DateField(help_text='Data do documento de movimentação para esta unidade escolar.', verbose_name='Data da CI de movimentação')),
                ('data_ingresso_unidade', models.DateField(help_text='Data em que o professor começou a trabalhar nesta escola.', verbose_name='Data de ingresso na unidade')),
                ('classificacao', models.PositiveIntegerField(blank=True, help_text='Ordem de chegada: 1 = professor com mais tempo na escola.', null=True, verbose_name='Classificação')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='professores/fotos/', verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo na escola')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de saída')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('disciplinas_lecionadas', models.ManyToManyField(blank=True, related_name='professores', to='professores.disciplina', verbose_name='Disciplinas que leciona na escola')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['classificacao', 'nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='HorarioProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.PositiveIntegerField(verbose_name='Ano letivo')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado')], max_length=10, verbose_name='Dia da semana')),
                ('hora_inicio', models.TimeField(verbose_name='Início')),
                ('hora_fim', models.TimeField(verbose_name='Fim')),
                ('local', models.CharField(choices=[('cabine_linguagens', 'Cabine de Linguagens'), ('cabine_matematica', 'Cabine de Matemática'), ('cabine_ciencias_natureza', 'Cabine de Ciências da Natureza'), ('cabine_ciencias_humanas', 'Cabine de Ciências Humanas'), ('auditorio', 'Auditório'), ('secretaria', 'Secretaria'), ('outro', 'Outro')], max_length=40, verbose_name='Local')),
                ('local_descricao', models.CharField(blank=True, help_text='Complemento se "Outro" for selecionado.', max_length=100, verbose_name='Descrição do local')),
                ('aprovado', models.BooleanField(default=False, help_text='Diretor marca como aprovado após revisão.', verbose_name='Aprovado pela Direção')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='professores.professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Horário do Professor',
                'verbose_name_plural': 'Horários dos Professores',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('professor', 'ano_letivo', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
