# Generated by Django 6.0.6 on 2026-08-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0004_professor_cargo_acumulacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='situacao_matricula_1',
            field=models.CharField(choices=[('ativo', 'Ativo(a)'), ('aposentado', 'Aposentado(a)'), ('licenca', 'Em Licença'), ('saida', 'Inativo / Transferido(a)')], default='ativo', max_length=20, verbose_name='Situação da 1ª Matrícula'),
        ),
        migrations.AddField(
            model_name='professor',
            name='situacao_matricula_2',
            field=models.CharField(choices=[('n_a', 'Não Possui 2ª Matrícula'), ('ativo', 'Ativo(a)'), ('aposentado', 'Aposentado(a)'), ('licenca', 'Em Licença'), ('saida', 'Inativo / Transferido(a)')], default='n_a', max_length=20, verbose_name='Situação da 2ª Matrícula'),
        ),
    ]
