# Generated by Django 6.0.6 on 2026-08-24 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0005_professor_situacao_matricula_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.PositiveIntegerField(help_text='Ex: 2026', unique=True, verbose_name='Ano Letivo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ano Letivo Atual / Ativo')),
                ('duracao_hora_aula', models.PositiveIntegerField(default=50, help_text='Padrão: 50 minutos', verbose_name='Duração da Hora/Aula (Minutos)')),
                ('horario_abertura', models.TimeField(default='07:00', verbose_name='Horário de Abertura')),
                ('horario_fechamento', models.TimeField(default='22:00', verbose_name='Horário de Fechamento')),
                ('func_segunda', models.BooleanField(default=True, verbose_name='Segunda-feira')),
                ('func_terca', models.BooleanField(default=True, verbose_name='Terça-feira')),
                ('func_quarta', models.BooleanField(default=True, verbose_name='Quarta-feira')),
                ('func_quinta', models.BooleanField(default=True, verbose_name='Quinta-feira')),
                ('func_sexta', models.BooleanField(default=True, verbose_name='Sexta-feira')),
                ('func_sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('func_domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações do Ano Letivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Escola',
                'verbose_name_plural': 'Configurações da Escola',
                'ordering': ['-ano_letivo'],
            },
        ),
        migrations.AlterModelOptions(
            name='horarioprofessor',
            options={'ordering': ['ano_letivo', 'dia_semana', 'hora_inicio'], 'verbose_name': 'Horário do Professor', 'verbose_name_plural': 'Horários dos Professores'},
        ),
        migrations.AlterUniqueTogether(
            name='horarioprofessor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='horarioprofessor',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='horarioprofessor',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='horarioprofessor',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprovado pela direção'),
        ),
        migrations.AlterField(
            model_name='horarioprofessor',
            name='local_descricao',
            field=models.CharField(blank=True, help_text='Ex: Sala 204, Auditório, etc.', max_length=100, verbose_name='Descrição do local'),
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_aula_semanais', models.PositiveIntegerField(default=4, verbose_name='Horas/Aula Semanais (50 min cada)')),
                ('carga_horaria_total', models.PositiveIntegerField(default=80, verbose_name='Carga Horária Total (Horas)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ofertada no Ano')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas_ofertadas', to='professores.configuracaoescola', verbose_name='Ano Letivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='professores.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina Ofertada',
                'verbose_name_plural': 'Disciplinas Ofertadas',
                'unique_together': {('configuracao', 'disciplina')},
            },
        ),
    ]
