# Generated by Django 6.0.6 on 2026-08-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0006_configuracaoescola_alter_horarioprofessor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoescola',
            name='dom_abertura',
            field=models.TimeField(default='08:00', verbose_name='Abertura Domingo'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='dom_fechamento',
            field=models.TimeField(default='12:00', verbose_name='Fechamento Domingo'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='qua_abertura',
            field=models.TimeField(default='08:50', verbose_name='Abertura Quarta'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='qua_fechamento',
            field=models.TimeField(default='20:30', verbose_name='Fechamento Quarta'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='qui_abertura',
            field=models.TimeField(default='08:50', verbose_name='Abertura Quinta'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='qui_fechamento',
            field=models.TimeField(default='20:30', verbose_name='Fechamento Quinta'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='sab_abertura',
            field=models.TimeField(default='08:00', verbose_name='Abertura Sábado'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='sab_fechamento',
            field=models.TimeField(default='12:00', verbose_name='Fechamento Sábado'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='seg_abertura',
            field=models.TimeField(default='08:50', verbose_name='Abertura Segunda'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='seg_fechamento',
            field=models.TimeField(default='20:30', verbose_name='Fechamento Segunda'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='sex_abertura',
            field=models.TimeField(default='08:50', verbose_name='Abertura Sexta'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='sex_fechamento',
            field=models.TimeField(default='17:00', verbose_name='Fechamento Sexta'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='ter_abertura',
            field=models.TimeField(default='08:50', verbose_name='Abertura Terça'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='ter_fechamento',
            field=models.TimeField(default='20:30', verbose_name='Fechamento Terça'),
        ),
    ]
