# Generated by Django 6.0.6 on 2026-08-24 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0007_configuracaoescola_dom_abertura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Unidade')),
                ('tipo', models.CharField(choices=[('sede', 'Sede Principal'), ('vinculada', 'Unidade Vinculada / Filial')], default='sede', max_length=20, verbose_name='Tipo de Unidade')),
                ('codigo', models.CharField(blank=True, max_length=30, verbose_name='Código / Sigla')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço Completo')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidade Escolar',
                'verbose_name_plural': 'Unidades Escolares',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='configuracaoescola',
            name='ano_letivo',
            field=models.PositiveIntegerField(help_text='Ex: 2026', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='configuracaoescola',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='professores.unidadeescolar', verbose_name='Unidade Escolar'),
        ),
        migrations.AddField(
            model_name='horarioprofessor',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_professores', to='professores.unidadeescolar', verbose_name='Unidade / Filial'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracaoescola',
            unique_together={('unidade', 'ano_letivo')},
        ),
    ]
