# Generated by Django 6.0.6 on 2026-08-26 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0008_unidadeescolar_alter_configuracaoescola_ano_letivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurmaComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_turma', models.CharField(help_text='Ex: CEJAS-C1L-080, CEJAS-E32-100', max_length=50, verbose_name='Código da Turma / Componente')),
                ('area', models.CharField(blank=True, help_text='Ex: Linguagens, Ciências da Natureza, Matemática, Ciências Humanas', max_length=150, verbose_name='Área do Conhecimento')),
                ('trilha_nucleo', models.CharField(blank=True, help_text='Ex: TRILHA DE APROFUNDAMENTO, NÚCLEO INTEGRADOR, ELETIVA 3 CATÁLOGO 2', max_length=200, verbose_name='Trilha de Aprofundamento / Núcleo Integrador')),
                ('disciplina_nome', models.CharField(help_text='Ex: COMPONENTE DE ÁREA 1 LINGUAGENS, CLUBE DA LEITURA', max_length=200, verbose_name='Nome da Disciplina / Componente')),
                ('tempos_requeridos', models.PositiveIntegerField(default=8, help_text='Quantidade de tempos a alocar no quadro (ex: 8 ou 10)', verbose_name='Carga Horária Exigida (em Tempos de 50 min)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='professores.configuracaoescola', verbose_name='Ano Letivo / Unidade')),
                ('disciplina_ofertada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='professores.disciplinaofertada', verbose_name='Disciplina Ofertada Relacionada')),
            ],
            options={
                'verbose_name': 'Turma / Componente Curricular',
                'verbose_name_plural': 'Turmas / Componentes Curriculares',
                'ordering': ['codigo_turma', 'disciplina_nome'],
            },
        ),
        migrations.CreateModel(
            name='AlocacaoHorarioTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado')], max_length=10, verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('hora_fim', models.TimeField(verbose_name='Horário de Fim')),
                ('rotulo_exibicao', models.CharField(blank=True, help_text='Nome customizado para exibição no quadro (ex: SANDRA, LUCIANA 1, DANIELA 2)', max_length=100, verbose_name='Rótulo de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_horario', to='professores.professor', verbose_name='Professor Alocado')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='professores.turmacomponente', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Alocação de Horário',
                'verbose_name_plural': 'Alocações de Horários',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('turma', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
