# Generated by Django 6.0.6 on 2026-08-27 22:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('professores', '0009_turmacomponente_alocacaohorarioturma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacaoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('texto', models.TextField(verbose_name='Anotação / Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anotação do Servidor',
                'verbose_name_plural': 'Anotações do Servidor',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200, verbose_name='Título / Descrição')),
                ('categoria', models.CharField(choices=[('atestado', 'Atestado Médico / Licença'), ('ausencia', 'Justificativa de Ausência'), ('folga', 'Comprovante de Folga / Compensação'), ('documento', 'Documento Pessoal / CI / Contrato'), ('outro', 'Outros Documentos')], default='documento', max_length=30, verbose_name='Categoria')),
                ('arquivo', models.FileField(upload_to='documentos_servidores/%Y/%m/', verbose_name='Arquivo')),
                ('data_documento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Documento / Ocorrência')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento do Servidor',
                'verbose_name_plural': 'Documentos do Servidor',
                'ordering': ['-data_documento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaFolgaServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('credito', '➕ Crédito de Folga (Direito Adquirido)'), ('usufruido', '➖ Gozo de Folga (Folga Usufruída)')], default='credito', max_length=20, verbose_name='Tipo de Lançamento')),
                ('dias', models.DecimalField(decimal_places=1, default=1.0, max_digits=5, verbose_name='Quantidade em Dias')),
                ('motivo', models.CharField(help_text='Ex: Trabalho na Eleição, Reunião Extra, Gozo de Folga', max_length=250, verbose_name='Motivo / Origem')),
                ('data_ocorrencia', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Ocorrência')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ocorrência de Folga do Servidor',
                'verbose_name_plural': 'Ocorrências de Folgas dos Servidores',
                'ordering': ['-data_ocorrencia', '-criado_em'],
            },
        ),
    ]
