# Generated by Django 6.0.6 on 2026-08-28 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0010_anotacaoservidor_documentoservidor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaohorarioturma',
            name='professor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_horario_secundario', to='professores.professor', verbose_name='2º Professor (Co-regência / Apoio)'),
        ),
        migrations.AlterField(
            model_name='alocacaohorarioturma',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_horario', to='professores.professor', verbose_name='1º Professor (Principal)'),
        ),
        migrations.AlterField(
            model_name='alocacaohorarioturma',
            name='rotulo_exibicao',
            field=models.CharField(blank=True, help_text='Nome customizado para exibição no quadro (ex: DELMA / MARCELO)', max_length=150, verbose_name='Rótulo de Exibição'),
        ),
    ]
