# Generated by Django 6.0.6 on 2026-09-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0011_alocacaohorarioturma_professor_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='tempos_aula',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade de tempos semanais de aula lecionados na escola pela 1ª matrícula.', null=True, verbose_name='Tempos de Aula (1ª Matrícula)'),
        ),
        migrations.AddField(
            model_name='professor',
            name='tempos_aula_acumulacao',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade de tempos semanais de aula lecionados na escola pela 2ª matrícula.', null=True, verbose_name='Tempos de Aula (2ª Matrícula)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='ch_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CH Total (1ª Matrícula)'),
        ),
    ]
