# Generated by Django 6.0.6 on 2026-09-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0012_professor_tempos_aula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaohorarioturma',
            name='vinculo_matricula_1',
            field=models.PositiveSmallIntegerField(default=1, help_text='Indica se a alocação do 1º professor refere-se à sua 1ª matrícula ou à 2ª matrícula.', verbose_name='Vínculo/Matrícula do 1º Professor (1 ou 2)'),
        ),
        migrations.AddField(
            model_name='alocacaohorarioturma',
            name='vinculo_matricula_2',
            field=models.PositiveSmallIntegerField(default=1, help_text='Indica se a alocação do 2º professor refere-se à sua 1ª matrícula ou à 2ª matrícula.', verbose_name='Vínculo/Matrícula do 2º Professor (1 ou 2)'),
        ),
        migrations.AddField(
            model_name='professor',
            name='acumulacao_nesta_escola',
            field=models.BooleanField(default=False, help_text='Marque se o professor leciona com as duas matrículas nesta unidade escolar.', verbose_name='2ª Matrícula leciona nesta escola (CEJA)?'),
        ),
    ]
