# Generated by Django 6.0.6 on 2026-09-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0013_alocacaohorarioturma_vinculo_matricula_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioprofessor',
            name='tipo_atividade',
            field=models.CharField(choices=[('docencia', 'Regência / Atendimento em Sala ou Cabine'), ('administrativa', 'Expediente Administrativo / Direção / Coordenação'), ('planejamento', 'Planejamento / Atividade Extraclasse'), ('outro', 'Outro')], default='docencia', max_length=30, verbose_name='Tipo de Atividade'),
        ),
        migrations.AddField(
            model_name='professor',
            name='ch_administrativa',
            field=models.PositiveIntegerField(blank=True, help_text='Horas semanais a cumprir na função administrativa (Ex: 40h, 30h, 20h).', null=True, verbose_name='Carga Horária Administrativa (Horas/Semana)'),
        ),
        migrations.AddField(
            model_name='professor',
            name='em_desvio_funcao',
            field=models.BooleanField(default=False, help_text='Indica se o professor atua em função administrativa em vez de lecionar em turmas.', verbose_name='Em Desvio de Função / Administrativo'),
        ),
        migrations.AddField(
            model_name='professor',
            name='funcao_administrativa',
            field=models.CharField(blank=True, choices=[('', 'Nenhuma / Regência em Sala (Docente)'), ('diretor_geral', 'Diretor Geral'), ('diretor_adjunto', 'Diretor Adjunto'), ('coordenador_pedagogico', 'Coordenador Pedagógico'), ('orientador_educacional', 'Orientador Educacional'), ('assistente_departamento_pessoal', 'Assistente de Departamento Pessoal'), ('outro', 'Outra Função Administrativa')], default='', help_text='Diretor Geral, Diretor Adjunto, Coordenador Pedagógico, Orientador Educacional, Assistente de DP, etc.', max_length=50, verbose_name='Função Administrativa / Gestão'),
        ),
        migrations.AddField(
            model_name='professor',
            name='funcao_administrativa_acumulacao',
            field=models.CharField(blank=True, choices=[('', 'Nenhuma / Regência em Sala (Docente)'), ('diretor_geral', 'Diretor Geral'), ('diretor_adjunto', 'Diretor Adjunto'), ('coordenador_pedagogico', 'Coordenador Pedagógico'), ('orientador_educacional', 'Orientador Educacional'), ('assistente_departamento_pessoal', 'Assistente de Departamento Pessoal'), ('outro', 'Outra Função Administrativa')], default='', help_text='Função administrativa da 2ª matrícula, caso atue em desvio de função.', max_length=50, verbose_name='Função Administrativa (2ª Matrícula)'),
        ),
        migrations.AlterField(
            model_name='horarioprofessor',
            name='local',
            field=models.CharField(choices=[('cabine_linguagens', 'Cabine de Linguagens'), ('cabine_matematica', 'Cabine de Matemática'), ('cabine_ciencias_natureza', 'Cabine de Ciências da Natureza'), ('cabine_ciencias_humanas', 'Cabine de Ciências Humanas'), ('auditorio', 'Auditório'), ('secretaria', 'Secretaria'), ('direcao_geral', 'Direção Geral / Gabinete'), ('direcao_adjunta', 'Direção Adjunta'), ('coordenacao_pedagogica', 'Coordenação Pedagógica'), ('orientacao_educacional', 'Orientação Educacional'), ('departamento_pessoal', 'Departamento Pessoal / RH'), ('outro', 'Outro')], max_length=40, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='horarioprofessor',
            name='local_descricao',
            field=models.CharField(blank=True, help_text='Ex: Sala 204, Gabinete, etc.', max_length=100, verbose_name='Descrição do local'),
        ),
    ]
