# Generated by Django 6.0.6 on 2026-09-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0014_horarioprofessor_tipo_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='abrangencia_desvio',
            field=models.CharField(choices=[('ambas', 'Ambas as Matrículas no Desvio (Acumulação Total no Cargo Administrativo)'), ('mat1', 'Apenas na 1ª Matrícula (2ª Matrícula continua em Sala de Aula)'), ('mat2', 'Apenas na 2ª Matrícula (1ª Matrícula continua em Sala de Aula)')], default='ambas', help_text='Define se ambas as matrículas acumulam no desvio ou se uma delas continua em sala de aula.', max_length=20, verbose_name='Abrangência do Desvio / Matrículas'),
        ),
    ]
