# Generated by Django 6.0.6 on 2026-09-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0015_professor_abrangencia_desvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='data_ci_movimentacao_acumulacao',
            field=models.DateField(blank=True, help_text='Data da CI referente à 2ª matrícula nesta escola.', null=True, verbose_name='Data da CI de Movimentação (2ª Matrícula)'),
        ),
        migrations.AddField(
            model_name='professor',
            name='data_ingresso_unidade_acumulacao',
            field=models.DateField(blank=True, help_text='Data de chegada nesta unidade escolar referente à 2ª matrícula.', null=True, verbose_name='Data de Chegada na Escola / Ingresso (2ª Matrícula)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='data_admissao_acumulacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Admissão no Estado (2ª Matrícula)'),
        ),
    ]
