# Generated by Django 6.0.6 on 2026-09-29 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0016_professor_data_ci_movimentacao_acumulacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anotacaoservidor',
            options={'ordering': ['-data_registro', '-criado_em'], 'verbose_name': 'Anotação do Servidor', 'verbose_name_plural': 'Anotações do Servidor'},
        ),
        migrations.AddField(
            model_name='anotacaoservidor',
            name='categoria',
            field=models.CharField(choices=[('geral', 'Observação Geral'), ('do', 'Publicação em Diário Oficial (D.O.)'), ('qualificacao', 'Qualificação / Titulação / Curso'), ('licenca', 'Licença / Afastamento / Atestado'), ('funcional', 'Evolução / Alteração Funcional'), ('elogio', 'Elogio / Mérito Funcional'), ('outro', 'Outro Registro Funcional')], default='geral', max_length=30, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='anotacaoservidor',
            name='data_registro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Ocorrência / Registro'),
        ),
        migrations.AddField(
            model_name='anotacaoservidor',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título / Assunto'),
        ),
    ]
