# Generated by Django 6.0.6 on 2026-10-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0017_alter_anotacaoservidor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoservidor',
            name='abrangencia_tipo',
            field=models.CharField(choices=[('dia_inteiro', 'Dia Inteiro / Dias'), ('tempos', 'Tempos de Aula (50 min cada)'), ('horas', 'Horas Cheias'), ('minutos', 'Minutos')], default='dia_inteiro', max_length=20, verbose_name='Abrangência do Atestado/Licença'),
        ),
        migrations.AddField(
            model_name='documentoservidor',
            name='lancar_banco_horas',
            field=models.BooleanField(default=False, verbose_name='Abater/Registrar no Banco de Horas'),
        ),
        migrations.AddField(
            model_name='documentoservidor',
            name='minutos_total',
            field=models.IntegerField(default=0, verbose_name='Minutos Totais'),
        ),
        migrations.AddField(
            model_name='documentoservidor',
            name='ocorrencia_folga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_anexados', to='professores.ocorrenciafolgaservidor', verbose_name='Lançamento no Banco de Horas'),
        ),
        migrations.AddField(
            model_name='documentoservidor',
            name='quantidade_tempo',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5, verbose_name='Quantidade de Tempo'),
        ),
        migrations.AddField(
            model_name='ocorrenciafolgaservidor',
            name='minutos',
            field=models.IntegerField(default=0, verbose_name='Quantidade em Minutos'),
        ),
        migrations.AddField(
            model_name='ocorrenciafolgaservidor',
            name='tempos_aula',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Tempos de Aula (50 min)'),
        ),
        migrations.AddField(
            model_name='ocorrenciafolgaservidor',
            name='unidade',
            field=models.CharField(choices=[('tempos', 'Tempos de Aula (50 min cada)'), ('minutos', 'Minutos'), ('horas', 'Horas Cheias'), ('dias', 'Dias')], default='dias', max_length=20, verbose_name='Unidade de Lançamento'),
        ),
    ]
