# Generated by Django 6.0.6 on 2026-09-01 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaCerebro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nova Consulta', max_length=255, verbose_name='Título da Conversa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Interação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_cerebro', to=settings.AUTH_USER_MODEL, verbose_name='Diretor')),
            ],
            options={
                'verbose_name': 'Conversa com a Beth',
                'verbose_name_plural': 'Conversas com a Beth',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCerebro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título / Nome do Documento')),
                ('categoria', models.CharField(choices=[('legislacao', '📜 Legislação & Resoluções'), ('regimento', '🏛️ Regimento Escolar & Normas'), ('pedagogico', '📚 Pedagógico & Avaliação'), ('gestao', '💼 Gestão & Administrativo'), ('horarios', '⏰ Horários & Funcionamento'), ('matricula', '🎓 Matrícula & Documentação de Alunos'), ('geral', '📋 Geral & Informações Diversas')], default='geral', max_length=30, verbose_name='Categoria')),
                ('tipo_arquivo', models.CharField(choices=[('pdf', 'PDF (.pdf)'), ('docx', 'Word (.docx)'), ('xlsx', 'Planilha Excel / CSV (.xlsx, .xls, .csv)'), ('audio', 'Gravação de Áudio (.mp3, .wav, .m4a, .ogg)'), ('imagem', 'Imagem / Print de Tela (.png, .jpg, .jpeg)'), ('texto', 'Nota de Texto / Legislação Direta')], default='texto', max_length=20, verbose_name='Tipo de Conteúdo')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='cerebro/documentos/%Y/%m/', verbose_name='Arquivo')),
                ('conteudo_extraido', models.TextField(blank=True, verbose_name='Texto Extraído / Conteúdo')),
                ('numero_normativa', models.CharField(blank=True, help_text='Exemplo: Portaria SEEDUC nº 123/2026, Resolução CEJA nº 04', max_length=100, verbose_name='Nº da Normativa / Portaria / Resolução')),
                ('ano_referencia', models.IntegerField(blank=True, null=True, verbose_name='Ano de Referência')),
                ('status', models.CharField(choices=[('vigente', '✅ Vigente / Ativo'), ('substituido', '🔄 Substituído / Revogado'), ('arquivado', '📦 Arquivado')], default='vigente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações da Direção')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cerebro_criados', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('documento_substituido', models.ForeignKey(blank=True, help_text='Se este documento revoga ou substitui outro documento anterior, selecione-o aqui.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituidores', to='orientador_ia.documentocerebro', verbose_name='Documento que este atualiza/substitui')),
            ],
            options={
                'verbose_name': 'Documento do Cérebro',
                'verbose_name_plural': 'Documentos do Cérebro',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FragmentoConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('indice_ordem', models.IntegerField(default=0)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='orientador_ia.documentocerebro')),
            ],
            options={
                'verbose_name': 'Fragmento de Conhecimento',
                'verbose_name_plural': 'Fragmentos de Conhecimento',
                'ordering': ['documento', 'indice_ordem'],
            },
        ),
        migrations.CreateModel(
            name='MensagemCerebro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(choices=[('usuario', 'Diretor(a)'), ('beth', 'Beth (Orientadora Virtual)')], max_length=20)),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('tipo_entrada', models.CharField(choices=[('texto', 'Texto'), ('audio', 'Voz / Áudio')], default='texto', max_length=20)),
                ('fontes_consultadas', models.JSONField(blank=True, default=list, null=True, verbose_name='Fontes Consultadas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='orientador_ia.conversacerebro')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['criado_em'],
            },
        ),
    ]
